// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace scottFrog.iOS
{
	public partial class Menu : UIView
	{
		public Menu (IntPtr handle) : base (handle)
		{
		}
	}
}
